### ISSUE TITLE
Jekyll is good idea as static website builder ?

### ISSUE THREAD

**Issue by AugustinMauroy** [valkey-io/valkey-io.github.io#11]
Jekyll is pretty cool to use and easy to deploy. But if you want to scale a project with component such as dropdown it's more complicated.
Also for i18N its isn't easy to maintain.

it's open question.

**Comment by madolson** [comment]
I think a lot of people are not that happy with Jekyll, I think the more commonly proposed alternative has been Hugo though.

**Comment by AugustinMauroy** [comment]
> I think a lot of people are not that happy with Jekyll, I think the more commonly proposed alternative has been Hugo though.

Hugo is cool.

**Comment by AugustinMauroy** [comment]
Honestly I'm huge fan of react.

So there are also [docusaurus](https://docusaurus.io/). it's easy to setup/maintain. It's also furnish I18n and searchbox. And keep advantage of react so we can just add one component if needed.

Also I'm fan of nextjs. So we can do something like done on [nodejs.org](https://github.com/nodejs/nodejs.org).

**Comment by dkbay** [comment]
I quite like https://starlight.astro.build/.
I'd be open to helping out a bunch with the website if it's swapped for something like that or vitepress etc. since I already have experience with those.
Will subscribe to the issues on here to see where this goes 👀

**Comment by AugustinMauroy** [comment]
> I quite like https://starlight.astro.build/. 

It's pretty cool to build easily maintainable.

**Comment by stockholmux** [comment]
Jekyll is setup right now and is, IMHO, sufficient for an initial version of the site which has some urgency.

Personally, I'm open to hearing options about other builders when the project isn't under pressure to get an initial version out, but otherwise the different options don't push towards getting the site out ASAP.

re: Hugo
I just got off working on an 800 page Hugo site, I'm not excited to do that again. The maintainability over time is pretty grim as Hugo doesn't have a coherent, stable versioning: they're on version 0.124.x and after 13 years have never pushed a 1.0.0. Breaking changes come at random times, the error messages are woefully poor, and it makes a lot of assumptions about how you should structure the site. It is fast though.

**Comment by dtaivpp** [comment]
I generally agree with the sentiment here. Jekyll is okay but the theming feels a bit dated. The other challenge and I am not sure this needs to be dealt with today is eventually the site reaches critical mass. By this I mean contributing to the OpenSearch website is challenging as it's several GB to pull with the images. 

I'm not sure its something that needs to be handled today but it would be good to think through a workflow for offloading images/graphics contributed to a some other image service so the site can remain lean. 

Starlight is interesting but it makes having an open source blog challenging as it doesn't seem to support pagination out of the box. 

Whatever is decided on I'd recommend a solution that supports blogs and documentation. While they don't need to be the same repo it will help as people tend to switch between docs and the site frequently. With that OpenSearch has struggled as our nav-bars are not the same between the docs page and the website.

**Comment by stockholmux** [comment]
Relevant for folks in this thread- help Valkey pick a colour pallet https://github.com/valkey-io/valkey-io.github.io/issues/55

**Comment by madolson** [comment]
I guess we moved to zola, so seems time to close this.
